version: "3.8"

services: 
  app:
    build: 
      image: oussemabes/docker-image:1.0.0
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_server
      PMA_USER: dan
      PMA_PASSWORD: secret
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - mysql_server


    
